// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WebLogic_10271(arg1) {
  return window['go']['exp']['Exp']['WebLogic_10271'](arg1);
}
